# ==============================================================================
# admin-frontend/service.yaml — Service ClusterIP pour le back-office admin
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bourse.fullname" . }}-admin-frontend
  labels:
    {{- include "bourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "bourse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin-frontend
