apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bourse.fullname" . }}-keycloak-realms
  labels:
    {{- include "bourse.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
data:
  realm-export.json: |
{{ .Files.Get "files/realm-export.json" | indent 4 }}
  realm-admin-export.json: |
{{ .Files.Get "files/realm-admin-export.json" | indent 4 }}
